name: Daily Scheduled Pipelines
# Pipelines that are scheduled every 24 hours

# disable until possible to run on docker runners
on:
  # schedule:
  #   - cron: "0 22 * * *"

env:
  AWS_SHARED_CREDENTIALS_CONTENT: ${{ secrets.AWS_SHARED_CREDENTIALS_FILE }}
  BAZEL_STARTUP_ARGS: "--output_base=/var/tmp/bazel-output/"
  CI_COMMIT_SHA: ${{ github.sha }}
  CI_COMMIT_REF_PROTECTED: ${{ github.ref_protected }}
  CI_JOB_NAME: ${{ github.job }}
  CI_JOB_ID: ${{ github.job }} # github does not expose this variable https://github.com/orgs/community/discussions/8945
  CI_JOB_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  CI_PIPELINE_SOURCE: ${{ github.event_name }}
  CI_PROJECT_DIR: ${{ github.workspace }}
  CI_MERGE_REQUEST_TARGET_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
  ROOT_PIPELINE_ID: ${{ github.run_id }}

jobs:
  rust-benchmarks:
    runs-on:
      labels: bazel-runner-large
    container:
      image: dfinity/ic-build:abbdc66c19bf32eda2109f97e39fde519ef9b452ab54aee52b234af8638983d8
    timeout-minutes: 720 # 12 hours
    if: ${{ vars.RUN_CI == 'true' }}
    strategy:
      matrix:
        targets: ["//rs/crypto/...", "//rs/state_manager/..."]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Rust Benchmarks
        id: rust-benchmarks
        shell: bash
        run: |
          ./gitlab-ci/src/ci-scripts/rust-benchmarks.sh
        env:
          BAZEL_CI_CONFIG: "--config=ci --repository_cache=/cache/bazel"
          BAZEL_COMMAND: "run"
          BAZEL_STARTUP_ARGS: "--output_base=/var/tmp/bazel-output/"
          RUSTFLAGS: "--remap-path-prefix=${CI_PROJECT_DIR}=/ic"
          RUST_BACKTRACE: "full"
          TARGETS: ${{ matrix.targets }}
